name: ci
on:
  push:
    branches:
      - master
      - 3.x
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin gh-pages --depth=1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-redirects
      - run: pip install mike
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - name: Deploy 2.x docs (master)
        if: github.ref == 'refs/heads/master'
        run: |
          mike deploy --push --update-aliases 2.x latest
          mike set-default --push latest
      - name: Deploy 3.x docs
        if: github.ref == 'refs/heads/3.x'
        run: mike deploy --push 3.x